### ISSUE TITLE
使用translate实现轮播图

### ISSUE THREAD

**Issue by isLishude** [isLishude/blog#99]
```html
 <div class="slider-wrap">
        <div class="slider-container">
            <div class="slider-item">
                <img src="./images/1.png" alt="">
            </div>
            <div class="slider-item">
                <img src="./images/2.png" alt="">
            </div>
            <div class="slider-item">
                <img src="./images/3.png" alt="">
            </div>
            <div class="slider-item">
                <img src="./images/4.png" alt="">
            </div>
        </div>
    </div>
```

```scss
* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

.slider-wrap {
    width: 700px;
    height: 500px;
    overflow: hidden;
    .slider-container {
        width: 2800px;
        transition: transform .5s linear;
        font-size: 0;
        .slider-item {
            display: inline-block;
            img {
                width: 700px;
                height: 500px;
            }
        }
    }
}
```

```js
'use strict'

var slider = document.querySelector('.slider-container')
var width = 700,
    move = 0,
    item = 4,
    flag = true;
var timer = setInterval(function () {
    if (Math.abs(move) === width * (item - 1)) {
        flag = false;
    } else if (move === 0) {
        flag = true;
    }
    if (Math.abs(move) < width * (item - 1) && flag) {
        move -= width;
        slider.style.transform = `translate(${move}px)`
    } else {
        move += width;
        slider.style.transform = `translate(${move}px)`
    }
}, 1500)
```
